version: '3.2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./assets/nginx/:/etc/nginx/conf.d/
    depends_on:
      - shortener

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  shortener:
    build:
      context: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_DB_URL=redis://redis:6379/0
      - DEBUG=0
      - HASHIDS_SALT=trololoqwerty
    ports:
      - "8888:8888"
volumes:
  redis_data: