version: '3.2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./assets/nginx/conf:/etc/nginx/conf.d/
      - ./assets/nginx/certs:/etc/nginx/certs/
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt

    depends_on:
      - shortener

  redis:
    image: redis:alpine

    volumes:
      - redis_data:/data

  shortener:
    build:
      context: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_DB_URL=redis://redis:6379/0
      - DEBUG=0
      - HASHIDS_SALT=${HASHIDS_SALT:-some_hash_default}
      - SHORTENER_URL=kamyanskiy.fvds.ru
    ports:
      - "8888:8888"
volumes:
  redis_data:
  certs:
  certs-data:
